module.exports = {
    COMMUNITY_CHAT: 'COMMUNITY_CHAT',
    USER_CONNECTED: 'USER_CONNECTED',
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_SEND: 'MESSAGE_SEND',
    USER_DICONNECTED: 'USER_DICONNECTED',
    TYPING: 'TYPING',
    VERIFY_USER: 'VERIFY_USER',
    LOGOUT: 'LOGOUT'
}